### PR TITLE
Fix checking for Windows

### PR DESCRIPTION
**Pull request by boudewijnrempt**

### CODE REVIEW

**Comment by dtschump** [comment]
Why removing 

    -    add_definitions(-Dcimg_appname=gmic)

?

**Comment by boudewijnrempt** [comment]
> Why removing 
> 
>     -    add_definitions(-Dcimg_appname=gmic)
> 
> ?

That gave a build error, for some weird reason. This whole block
of cmake code was never executed before...

-- 
Boudewijn Rempt | http://www.krita.org, http://www.valdyas.org

**Comment by dtschump** [comment]
Which error ? It shouldn't, and this is a macro that should keep its value of `gmic` when compiling G'MIC, so it's better to try fixing the issue rather than removing that definition :)

**Comment by boudewijnrempt** [comment]
On Thu, 24 Aug 2017, David Tschumperlé wrote:

> Which error ? It shouldn't, and this is a macro that should keep its value of `gmic` when compiling G'MIC, so it's better to try fixing the issue rather than removing that definition :)
> 


This is the error:


In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h: In constructor 'cimg_library::CImg<T>::_cimg_math_parser::_cimg_math_parser(const char*, const char*, const cimg_library::CImg<T>&, cimg_library::CImg<T>*, const cimg_library::CImgList<T>*, cimg_library::CImgList<T>*, bool)':
C:/dev/gmic/src/CImg.h:15171:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                      ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:15171:43: note: in expansion of macro 'cimg_appname'
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                           ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h: In member function 'cimg_library::CImg<typename cimg_library::cimg::last<T, unsigned int>::type> cimg_library::CImg<T>::_cimg_math_parser::get_level(cimg_library::CImg<typename cimg_library::cimg::last<T, char>::type>&) const':
C:/dev/gmic/src/CImg.h:15320:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                      ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:15320:43: note: in expansion of macro 'cimg_appname'
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                           ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:15327:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                      ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:15327:43: note: in expansion of macro 'cimg_appname'
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                           ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h: In member function 'unsigned int cimg_library::CImg<T>::_cimg_math_parser::compile(char*, char*, unsigned int, unsigned int*)':
C:/dev/gmic/src/CImg.h:15360:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                      ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:15360:43: note: in expansion of macro 'cimg_appname'
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                           ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:15384:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                      ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:15384:43: note: in expansion of macro 'cimg_appname'
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                           ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:15804:48: error: expected primary-expression before '(' token
                     throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:15804:53: note: in expansion of macro 'cimg_appname'
                     throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                     ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:15826:48: error: expected primary-expression before '(' token
                     throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:15826:53: note: in expansion of macro 'cimg_appname'
                     throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                     ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:15970:46: error: expected primary-expression before '(' token
                   throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                              ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:15970:51: note: in expansion of macro 'cimg_appname'
                   throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                   ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:16133:40: error: expected primary-expression before '(' token
             throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                        ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:16133:45: note: in expansion of macro 'cimg_appname'
             throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                             ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:16359:40: error: expected primary-expression before '(' token
             throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                        ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:16359:45: note: in expansion of macro 'cimg_appname'
             throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                             ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:16996:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                      ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:16996:43: note: in expansion of macro 'cimg_appname'
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                           ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:17092:42: error: expected primary-expression before '(' token
               throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                          ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:17092:47: note: in expansion of macro 'cimg_appname'
               throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                               ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:17123:42: error: expected primary-expression before '(' token
               throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                          ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:17123:47: note: in expansion of macro 'cimg_appname'
               throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                               ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:17621:44: error: expected primary-expression before '(' token
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                            ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:17621:49: note: in expansion of macro 'cimg_appname'
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                 ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:17661:46: error: expected primary-expression before '(' token
                   throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                              ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:17661:51: note: in expansion of macro 'cimg_appname'
                   throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                   ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:18331:44: error: expected primary-expression before '(' token
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                            ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:18331:49: note: in expansion of macro 'cimg_appname'
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                 ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:18434:44: error: expected primary-expression before '(' token
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                            ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:18434:49: note: in expansion of macro 'cimg_appname'
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                 ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:18524:46: error: expected primary-expression before '(' token
                   throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                              ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:18524:51: note: in expansion of macro 'cimg_appname'
                   throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                   ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:18728:44: error: expected primary-expression before '(' token
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                            ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:18728:49: note: in expansion of macro 'cimg_appname'
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                 ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:18761:46: error: expected primary-expression before '(' token
                   throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                              ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:18761:51: note: in expansion of macro 'cimg_appname'
                   throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                   ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:18837:44: error: expected primary-expression before '(' token
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                            ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:18837:49: note: in expansion of macro 'cimg_appname'
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                 ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:18890:44: error: expected primary-expression before '(' token
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                            ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:18890:49: note: in expansion of macro 'cimg_appname'
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                 ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:19243:44: error: expected primary-expression before '(' token
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                            ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:19243:49: note: in expansion of macro 'cimg_appname'
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                 ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:19251:44: error: expected primary-expression before '(' token
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                            ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:19251:49: note: in expansion of macro 'cimg_appname'
                 throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                                 ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:19281:40: error: expected primary-expression before '(' token
             throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                        ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:19281:45: note: in expansion of macro 'cimg_appname'
             throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                             ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:19484:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                      ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:19484:43: note: in expansion of macro 'cimg_appname'
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                           ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:19491:36: error: expected primary-expression before '(' token
         throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                    ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:19491:41: note: in expansion of macro 'cimg_appname'
         throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                         ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h: In member function 'void cimg_library::CImg<T>::_cimg_math_parser::check_constant(unsigned int, unsigned int, unsigned int, char*, char*, char)':
C:/dev/gmic/src/CImg.h:19873:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                      ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:19873:43: note: in expansion of macro 'cimg_appname'
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                           ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
           ic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h: In member function 'void cimg_library::CImg<T>::_cimg_math_parser::check_list(bool, char*, char*, char)':
C:/dev/gmic/src/CImg.h:19956:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                      ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:19956:43: note: in expansion of macro 'cimg_appname'
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                           ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h: In member function 'void cimg_library::CImg<T>::_cimg_math_parser::check_vector0(unsigned int, char*, char*, char)':
C:/dev/gmic/src/CImg.h:19972:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                      ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:19972:43: note: in expansion of macro 'cimg_appname'
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                           ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h:19981:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                      ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:19981:43: note: in expansion of macro 'cimg_appname'
           throw CImgArgumentException("[" cimg_appname "_math_parser] "
                                           ^
C:/dev/gmic/src/CImg.h: In static member function 'static double cimg_library::CImg<T>::_cimg_math_parser::mp_debug(cimg_library::CImg<T>::_cimg_math_parser&)':
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:20272:30: note: in expansion of macro 'cimg_appname'
                        "\n[" cimg_appname "_math_parser] %p[thread #%u]:%*c"
                              ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:20295:32: note: in expansion of macro 'cimg_appname'
                          "\n[" cimg_appname "_math_parser] %p[thread #%u]:%*c"
                                ^
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:20307:19: note: in expansion of macro 'cimg_appname'
             "\n[" cimg_appname "_math_parser] %p[thread #%u]:%*c"
                   ^
C:/dev/gmic/src/CImg.h: In static member function 'static double cimg_library::CImg<T>::_cimg_math_parser::mp_display_memory(cimg_library::CImg<T>::_cimg_math_parser&)':
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:20338:28: note: in expansion of macro 'cimg_appname'
         mp.mem.display("[" cimg_appname "_math_parser] Memory snapshot");
                            ^
C:/dev/gmic/src/CImg.h: In static member function 'static double cimg_library::CImg<T>::_cimg_math_parser::mp_display(cimg_library::CImg<T>::_cimg_math_parser&)':
<command-line>:0:14: error: expected ')' before 'gmic'
C:/dev/gmic/src/CImg.h:20361:35: note: in expansion of macro 'cimg_appname'
         ((CImg<charT>::string("[" cimg_appname "_math_parser] ",false,true),expr)>'x').move_to(expr);
                                   ^
In file included from C:/dev/gmic/src/gmic.h:174:0,
                 from C:\dev\gmic-qt\src\ParametersCache.cpp:34:
C:/dev/gmic/src/CImg.h: In static member function 'static double cimg_library::CImg<T>::_cimg_math_parser::mp_image_draw(cimg_library::CImg<T>::_cimg_math_parser&)':
C:/dev/gmic/src/CImg.h:20662:38: error: expected primary-expression before '(' token
           throw CImgArgumentException("[" cimg_appname "_math_parser] CImg<%s>: Function 'draw()'::get_select_graph(cimg_library::CImgDisplay&, unsigned int, unsigned int, const char*, double, double, const char*, double, double, bool) const':
<command-line>:0:14: error: 'gmic' was not declared in this scope
C:/dev/gmic/src/CImg.h:47688:56: note: in expansion of macro 'cimg_appname'
                 cimg_snprintf(filename,filename._width,cimg_appname "_%.4u.bmp",snap_number++);
                                                        ^
<command-line>:0:14: note: suggested alternative: 'min'
C:/dev/gmic/src/CImg.h:47688:56: note: in expansion of macro 'cimg_appname'
                 cimg_snprintf(filename,filename._width,cimg_appname "_%.4u.bmp",snap_number++);
                                                        ^
<command-line>:0:14: error: 'gmic' was not declared in this scope
C:/dev/gmic/src/CImg.h:47704:56: note: in expansion of macro 'cimg_appname'
                 cimg_snprintf(filename,filename._width,cimg_appname "_%.4u.cimgz",snap_number++);
                                                        ^
<command-line>:0:14: note: suggested alternative: 'min'
C:/dev/gmic/src/CImg.h:47704:56: note: in expansion of macro 'cimg_appname'
                 cimg_snprintf(filename,filename._width,cimg_appname "_%.4u.cimgz",snap_number++);
                                                        ^
C:/dev/gmic/src/CImg.h: In member function 'const cimg_library::CImg<T>& cimg_library::CImg<T>::_display_object3d(cimg_library::CImgDisplay&, const char*, const cimg_library::CImg<t>&, const cimg_library::CImgList<tf>&, const cimg_library::CImgList<tc>&, const to&, bool, int, int, bool, float, float, float, float, float, float, bool, float*, bool) const':
<command-line>:0:14: error: 'gmic' was not declared in this scope
C:/dev/gmic/src/CImg.h:51780:54: note: in expansion of macro 'cimg_appname'
               cimg_snprintf(filename,filename._width,cimg_appname "_%.4u.bmp",snap_number++);
                                                      ^
<command-line>:0:14: note: suggested alternative: 'min'
C:/dev/gmic/src/CImg.h:51780:54: note: in expansion of macro 'cimg_appname'
               cimg_snprintf(filename,filename._width,cimg_appname "_%.4u.bmp",snap_number++);
                                                      ^
<command-line>:0:14: error: 'gmic' was not declared in this scope
C:/dev/gmic/src/CImg.h:51794:54: note: in expansion of macro 'cimg_appname'
               cimg_snprintf(filename,filename._width,cimg_appname "_%.4u.off",snap_number++);
                                                      ^
<command-line>:0:14: note: suggested alternative: 'min'
C:/dev/gmic/src/CImg.h:51794:54: note: in expansion of macro 'cimg_appname'
               cimg_snprintf(filename,filename._width,cimg_appname "_%.4u.off",snap_number++);
                                                      ^
<command-line>:0:14: error: 'gmic' was not declared in this scope
C:/dev/gmic/src/CImg.h:51809:54: note: in expansion of macro 'cimg_appname'
               cimg_snprintf(filename,filename._width,cimg_appname "_%.4u.cimgz",snap_number++);
                                                      ^
<command-line>:0:14: note: suggested alternative: 'min'
C:/dev/gmic/src/CImg.h:51809:54: note: in expansion of macro 'cimg_appname'
               cimg_snprintf(filename,filename._width,cimg_appname "_%.4u.cimgz",snap_number++);
                                                      ^
C:/dev/gmic/src/CImg.h: In member function 'cimg_library::CImg<typename cimg_library::cimg::last<T, int>::type> cimg_library::CImgList<T>::_select(cimg_library::CImgDisplay&, const char*, bool, char, float, bool, unsigned int, bool, bool, bool) const':
<command-line>:0:14: error: 'gmic' was not declared in this scope
C:/dev/gmic/src/CImg.h:56859:54: note: in expansion of macro 'cimg_appname'
               cimg_snprintf(filename,filename._width,cimg_appname "_%.4u.bmp",snap_number++);
                                                      ^
<command-line>:0:14: note: suggested alternative: 'min'
C:/dev/gmic/src/CImg.h:56859:54: note: in expansion of macro 'cimg_appname'
          
> 

-- 
Boudewijn Rempt | http://www.krita.org, http://www.valdyas.org

**Comment by dtschump** [comment]
I see.
The value of the macro `cimg_appname` must be `"gmic"` (with the double quotes), and not `gmic`.
Adding the double quotes will probably fix the issue.

**Comment by boudewijnrempt** [comment]
> The value of the macro `cimg_appname` must be `"gmic"` (with the double quotes), and not `gmic`.
> Adding the double quotes will probably fix the issue.

Ah! That seems to work indeed. I'll prepare a new patch.

-- 
Boudewijn Rempt | http://www.krita.org, http://www.valdyas.org

**Pull request closed without merging**
