### PR TITLE
Support compilation using system libgmic and CImg 

### PR DESCRIPTION
**Pull request by amyspark**
:wave:

This PR upstreams the patches enabling building Krita's G'MIC-Qt using system libgmic and CImg. These were provided originally by @darix and @cryptomilk, with a recent bugfix by @antonio-rojas for G'MIC-Qt 3.1.4.

The attached commits are extensions of the below PRs, which will be closed as completed.

Closes #134
Closes #81

cc @dtschump @c-koi

### CODE REVIEW

**Comment by darix** [comment]
oh i was planning to refresh my PR over the weekend. thank you for doing it :)

**Comment by dtschump** [comment]
We don't really get what is your goal with this PR.
Could you explain it.
In what it is different from compiling with `GMIC_DYNAMIC_LINKING=on` ?

**Comment by amyspark** [comment]
>  In what it is different from compiling with GMIC_DYNAMIC_LINKING=on ?

That's only available in the qmake toolchain, and is Linux only.

**Comment by dtschump** [comment]
> That's only available in the qmake toolchain, and is Linux only. Also cc @antonio-rojas and @darix for more context.

Well, but why having to change all these files to make it work for other platforms than Linux?
In particular, I don't see the point with:
~~~
#ifndef gmic_core
#include "CImg.h"
#endif
#include "gmic.h"
~~~
that appears in most `.cpp` files.

**Comment by dtschump** [comment]
I see you want to remove the definition of `gmic_core` when compiling, so that's probably the reason why all these extra "CImg.h" includes are necessary.
But why trying to remove `gmic_core` ? What problem does it solve?

**Comment by dtschump** [comment]
Ha I guess, that's because you don't want `gmic.h` depends on `gmic.cpp`...

**Comment by dtschump** [comment]
@c-koi , maybe we can wait for @amyspark 's answer, but if so, the PR seems correct to me.
It allows G'MIC-Qt to be compiled in `GMIC_DYNAMIC_LINKING=on` mode without requiring a dependency to `gmic.cpp`, which is nice.
The change to be made in the `gmic-qt.pro` file should be only to undefine `gmic_core` when `GMIC_DYNAMIC_LINKING=on` (as you did on ZArt a few days ago).

**Comment by cryptomilk** [comment]
The krita5 gmic plugin links against libgmic, We want to build with the header files and library provided by a gmic package and not do a in-source build in the gmic sources.

**Comment by darix** [comment]
Krita forked gmic-qt for their integration into krita. Due to the way gmic-qt was built it included the gmic.cpp file and as such it was recompiled over and over. in an ideal world a distro builds one gmic package. and gmic-qt is a separate package that links against the gmic-devel package.

And then building krita's gmic integration becomes very simple without n compiled copies of gmic.cpp on a system.

**Comment by dtschump** [comment]
I understand.
It looks good to me. @c-koi , I suggest this PR gets merged.

**Pull request merged**
