### PR TITLE
 PR to include gmic git repository as a git submodule.

### PR DESCRIPTION
**Pull request by cgilles**
Hi,

Cloning gmic-qt will automatically clone internally gmic repository. Root CmakeLists.txt will check now this path to found gmic headers.

It's definitively more simple to clone 2 separate repositories to compile gmic-qt

Best

Gilles Caulier

### CODE REVIEW

**Comment by cgilles** [comment]
Note : after to clone gmic-qt with this PR, you need to init submodule like this : 

git submodule update --init

Gilles Caulier

**Comment by c-koi** [comment]
Thanks for the suggestions.
I'm fine only with commits f02cae7 (mentioning DigiKam in the message would be great) and c62704e though.
Should I make the modifications myself or would you send a (minimal & clean) PR?

**Comment by cgilles** [comment]
you can patch these 2 commits directly i will sync later my fork

**Comment by cgilles** [comment]
Q: why the git sub module workound to checkout cimg and gmic repositories automatically are not accepted. It will help and simplify a lots end user life which checkout gmic-qt to compile code on a target computer.

I work on this solution because the already implemented way hardcoded in makefile from gmic and cmig projects use wget which are not installed de facto in virtual cloud system to compute bundles, as appimage, flatpak, or snap for Linux. It's for security reasons. The only way is to checkout with git url.

Gilles Caulier

**Pull request closed without merging**
