### PR TITLE
Add new digiKam host application

### PR DESCRIPTION
**Pull request by cgilles**
Hi,

Since one week, i work to port GMic-Qt plugin to digiKam. The first version is now finalized.

Screenshot of this plugin in action : https://imgur.com/PmuvJwx

It require the current digiKam implementation from git/master to compile, which will be the next digiKam 6.3.0 release plan in few weeks.

Thanks to considerate this pull request

Best

Gilles Caulier

### CODE REVIEW

**Comment by dtschump** [comment]
Hi Gilles, What a wonderful idea ! :+1: 
Is there any limitations right now on the use of the plug-in in Digikam (like multi-layers input/output maybe ?).

It's really great news!

**Comment by cgilles** [comment]
yes, digiKam image editor and Showfoto do not support mult-ilayer, but it's not a problem. We only work on single main image as well...

It still a feature not yes implemented in the plugin : Color Management support. It planed for a next PR...

**Comment by cgilles** [comment]
Update of previous PR including fixes 16 bits colors depth support, C++ exceptions support,  fix authors list, fix README.md, remove bootstrap.sh script

**Comment by c-koi** [comment]
Thanks for this nice contribution. Welcome digiKam!

**Pull request merged**
